/**
 * Tap Payments API helpers — server-side only.
 *
 * Tap API reference: https://developers.tap.company/reference
 *
 * Currency: USD (major units, e.g. 49 = USD 49.00).
 * Model: server-initiated hosted checkout (redirect-based).
 *
 * Flow:
 *   1. Server calls createCharge() → gets charge.transaction.url
 *   2. Server redirects customer to transaction.url (Tap hosted page)
 *   3. Tap redirects customer back to /checkout/return?tap_id=<charge_id>
 *   4. Return handler calls retrieveCharge() to re-fetch status (never trust query params)
 *   5. Tap also POSTs to /api/tap/webhook for out-of-band reconciliation
 *
 * NEVER import this file in Client Components.
 */
import { config } from "@/lib/config";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TapCustomer {
  first_name: string;
  last_name: string;
  email: string;
  phone?: {
    country_code: string; // e.g. "971" (no +)
    number: string;       // e.g. "501234567"
  };
}

export interface TapChargeInput {
  /** Amount in USD major units (e.g. 49 = USD 49.00) */
  amount: number;
  /** Human-readable plan description */
  description: string;
  /** Short descriptor on bank statement — max 22 chars */
  statementDescriptor?: string;
  customer: TapCustomer;
  /**
   * Metadata stored on the charge for reconciliation.
   * plan, cycle, product, display, plan_name per spec.
   */
  metadata: {
    plan: string;
    cycle: string;
    product: string;
    display: string;
    plan_name: string;
    [key: string]: string;
  };
  /** Where Tap redirects the customer after payment (carries ?tap_id=charge_id) */
  redirectUrl: string;
  /** Server-to-server per-charge callback URL */
  postUrl?: string;
  /** Unique transaction reference (generated by caller) */
  transactionRef?: string;
  /** Unique order reference (generated by caller) */
  orderRef?: string;
}

export interface TapChargeResponse {
  id: string;
  status: string; // INITIATED | CAPTURED | AUTHORIZED | IN_PROGRESS | PENDING | CANCELLED | FAILED | DECLINED | ABANDONED | REFUNDED
  amount: number;
  currency: string;
  description?: string;
  metadata?: Record<string, string>;
  reference?: {
    transaction?: string;
    order?: string;
    gateway?: string;
    payment?: string;
  };
  transaction: {
    url: string;     // Tap hosted payment page — redirect user here
    created?: string;
    asof?: string;
  };
  response?: {
    code?: string;
    message?: string;
  };
  customer?: {
    first_name?: string;
    last_name?: string;
    email?: string;
  };
}

export interface TapError {
  errors?: Array<{ code?: string; description?: string }>;
}

/**
 * Maps a raw Tap charge status to the internal order status.
 *
 * Tap status       → Internal status
 * CAPTURED/AUTHORIZED → paid
 * INITIATED/IN_PROGRESS/PENDING → initiated
 * CANCELLED        → cancelled
 * anything else    → failed
 */
export type OrderStatus = "initiated" | "paid" | "failed" | "cancelled" | "refunded" | "partially_refunded" | "refunding";

export function mapTapStatus(tapStatus: string): OrderStatus {
  const s = tapStatus?.toUpperCase();
  if (s === "CAPTURED" || s === "AUTHORIZED") return "paid";
  if (s === "INITIATED" || s === "IN_PROGRESS" || s === "PENDING") return "initiated";
  if (s === "CANCELLED") return "cancelled";
  if (s === "REFUNDED") return "refunded";
  return "failed";
}

// ---------------------------------------------------------------------------
// Phone number parser
// ---------------------------------------------------------------------------

/**
 * Parses a raw phone string into Tap's required { country_code, number } format.
 * Tap expects country_code WITHOUT the leading + (e.g. "971" not "+971").
 *
 * Examples:
 *  "+971 501234567"  → { country_code: "971", number: "501234567" }
 *  "+96896737452"    → { country_code: "968", number: "96737452" }
 *  "00971501234567"  → { country_code: "971", number: "501234567" }
 *  "501234567"       → { country_code: "971", number: "501234567" } (defaults to UAE)
 *  "1 5551234567"    → { country_code: "1",   number: "5551234567" }
 */
export function parseTapPhone(raw: string): { country_code: string; number: string } {
  const cleaned = raw.trim().replace(/\s+/g, "");
  const normalized = cleaned.startsWith("00") ? "+" + cleaned.slice(2) : cleaned;

  if (!normalized.startsWith("+")) {
    return { country_code: "971", number: normalized };
  }

  const digits = normalized.slice(1);
  const knownCodes: Record<string, number> = {
    "966": 3, "971": 3, "968": 3, "974": 3, "973": 3, "965": 3, "967": 3, "962": 3,
    "963": 3, "964": 3, "961": 3, "970": 3, "972": 3, "212": 3, "213": 3,
    "216": 3, "218": 3, "249": 3, "252": 3,
    "20": 2, "44": 2, "49": 2, "33": 2, "39": 2, "34": 2,
    "1": 1,
  };

  for (const len of [3, 2, 1]) {
    const candidate = digits.slice(0, len);
    if (knownCodes[candidate] !== undefined) {
      return { country_code: candidate, number: digits.slice(len) };
    }
  }

  return { country_code: digits.slice(0, 3), number: digits.slice(3) };
}

// ---------------------------------------------------------------------------
// Reference generators
// ---------------------------------------------------------------------------

/** Generates a unique transaction reference: txn_<slug>_<cycle>_<ts> */
export function generateTransactionRef(plan: string, cycle: string): string {
  const slug = plan.replace(/[^a-z0-9]/gi, "-").toLowerCase();
  const cyc = cycle.replace(/[^a-z0-9]/gi, "-").toLowerCase();
  return `txn_${slug}_${cyc}_${Date.now()}`;
}

/** Generates a unique order reference: ord_<ts>_<rand> */
export function generateOrderRef(): string {
  const rand = Math.random().toString(36).slice(2, 8);
  return `ord_${Date.now()}_${rand}`;
}

// ---------------------------------------------------------------------------
// API helpers
// ---------------------------------------------------------------------------

const TAP_API_BASE = "https://api.tap.company/v2";

function tapHeaders(): HeadersInit {
  const key = config.tap.secretKey;
  if (!key) throw new Error("TAP_SECRET_KEY is not configured.");
  // Warn if it looks like a publishable key
  if (!key.startsWith("sk_")) {
    console.warn("[tap] TAP_SECRET_KEY looks like a publishable key (should start with sk_)");
  }
  return {
    Authorization: `Bearer ${key}`,
    "Content-Type": "application/json",
    Accept: "application/json",
  };
}

/**
 * Creates a Tap charge and returns the charge object including the hosted
 * payment page URL. The caller should 303-redirect the user to
 * `charge.transaction.url`.
 *
 * If transaction.url is missing from the response, returns { ok: false }.
 */
export async function createTapCharge(
  input: TapChargeInput,
): Promise<{ ok: true; charge: TapChargeResponse } | { ok: false; error: string }> {
  const {
    amount,
    description,
    statementDescriptor = "SmarThinkerz",
    customer,
    metadata,
    redirectUrl,
    postUrl,
    transactionRef,
    orderRef,
  } = input;

  const body: Record<string, unknown> = {
    amount,
    currency: "USD",
    threeDSecure: true,
    save_card: false,
    description,
    statement_descriptor: statementDescriptor,
    metadata,
    reference: {
      transaction: transactionRef ?? generateTransactionRef(metadata.plan, metadata.cycle),
      order: orderRef ?? generateOrderRef(),
    },
    receipt: { email: true, sms: false },
    customer: {
      first_name: customer.first_name,
      last_name: customer.last_name,
      email: customer.email,
      ...(customer.phone
        ? { phone: { country_code: customer.phone.country_code, number: customer.phone.number } }
        : {}),
    },
    source: { id: "src_all" },
    redirect: { url: redirectUrl },
    ...(postUrl ? { post: { url: postUrl } } : {}),
  };

  try {
    const res = await fetch(`${TAP_API_BASE}/charges`, {
      method: "POST",
      headers: tapHeaders(),
      body: JSON.stringify(body),
    });

    const data = await res.json();

    if (!res.ok) {
      const tapErr = data as TapError;
      const msg =
        tapErr.errors?.[0]?.description ??
        `Tap API error ${res.status}: ${JSON.stringify(data)}`;
      console.error("[tap] createTapCharge error:", msg);
      return { ok: false, error: msg };
    }

    const charge = data as TapChargeResponse;

    // Spec: if transaction.url is missing, return 502 — we surface as error
    if (!charge.transaction?.url) {
      console.error("[tap] createTapCharge: missing transaction.url in response", data);
      return { ok: false, error: "Tap did not return a payment URL. Please try again." };
    }

    return { ok: true, charge };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[tap] createTapCharge network error:", msg);
    return { ok: false, error: msg };
  }
}

/**
 * Retrieves a charge by ID from Tap.
 * Used by the /checkout/return handler to re-fetch the authoritative status.
 * NEVER trust the tap_id query param directly — always re-fetch.
 */
export async function retrieveCharge(
  chargeId: string,
): Promise<{ ok: true; charge: TapChargeResponse } | { ok: false; error: string }> {
  try {
    const res = await fetch(`${TAP_API_BASE}/charges/${chargeId}`, {
      method: "GET",
      headers: tapHeaders(),
    });

    const data = await res.json();

    if (!res.ok) {
      const tapErr = data as TapError;
      const msg = tapErr.errors?.[0]?.description ?? `Tap API error ${res.status}`;
      return { ok: false, error: msg };
    }

    return { ok: true, charge: data as TapChargeResponse };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return { ok: false, error: msg };
  }
}

/**
 * Issues a refund for a charge.
 * POST /v2/refunds
 */
export async function refundCharge(
  chargeId: string,
  amount: number,
  reason = "requested_by_customer",
): Promise<{ ok: true; refundId: string } | { ok: false; error: string }> {
  try {
    const res = await fetch(`${TAP_API_BASE}/refunds`, {
      method: "POST",
      headers: tapHeaders(),
      body: JSON.stringify({ charge_id: chargeId, amount, currency: "USD", reason }),
    });

    const data = await res.json();

    if (!res.ok) {
      const tapErr = data as TapError;
      const msg = tapErr.errors?.[0]?.description ?? `Tap refund error ${res.status}`;
      return { ok: false, error: msg };
    }

    return { ok: true, refundId: (data as { id: string }).id };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return { ok: false, error: msg };
  }
}

// Keep legacy export alias for any existing callers
export { retrieveCharge as getTapCharge };
